spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/kitedb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.threads.virtual.enabled=true
spring.security.user.name=matt
spring.security.user.password=pw
spring.app.jwtSecret=dbd478bb58b870281374e4d649a2ee8b30e43fdc2a06eb113b460024da05fd75
spring.app.jwtExpirationMs=604800000
scalar.enabled=true
springdoc.api-docs.path=/v3/api-docs
scalar.url=/v3/api-docs
scalar.path=/scalar